service:
  type: ClusterIP
  port: 3000
replicaCount: 1
podLabels:
  app: beauty-ai
image:
  repository: ghcr.io/santiagobosque/ai-beauty
  tag: sha-42ac8841f2fd
imagePullSecrets:
  - name: ghcr-cred

ingress:
  enabled: true
  className: traefik
  annotations: {}
  hosts:
    - host: app.10.10.10.233.nip.io
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 1
    memory: 512Mi