apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/santiagobosque/infra-platform.git
      targetRevision: main
      path: k8s/charts/myapp
      helm:
        valueFiles:
          - $values/k8s/values/dev/myapp.yaml
    - repoURL: https://github.com/santiagobosque/infra-platform.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true